version: '3.1'
services:
    cloud9-aws:
        build: .
        container_name: cloud9-aws
        volumes:
            - ./workspace:/workspace
        environment:
            USERNAME: user
            PASSWORD: pass
        ports:
            - "80:8080"
